---
- name: Deploy Docker container on remote server
  hosts: 192.168.1.93 
  become: true  # Use sudo if necessary

  tasks:
    - name: Ensure Docker image is available on the remote server
      docker_image:
        name: "{{ image }}"
        source: pull  # This will pull the image if it's not already available
        state: present  # Ensure the image is present on the host

    - name: Stop existing Docker container
      docker_container:
        name: my-container
        state: stopped
        ignore_errors: yes

    - name: Remove existing Docker container
      docker_container:
        name: my-container
        state: absent
        ignore_errors: yes

    - name: Run Docker container
      docker_container:
        name: my-container
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"  # Example port forwarding
