- name: Deploy Docker container on remote server
  hosts: 192.168.1.93
  become: true

  tasks:
    - name: Load Docker image from tar file
      command: docker load -i /home/vivek/{{ image }}.tar
      register: load_result

    - name: Check if image was loaded successfully
      fail:
        msg: "Failed to load Docker image: {{ load_result.stderr }}"
      when: load_result.rc != 0

    - name: Stop and remove existing container (if exists)
      docker_container:
        name: my-container
        state: absent
        ignore_errors: yes

    - name: Run Docker container
      docker_container:
        name: my-container
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - container_port: 80
            host_port: 80
