- name: Deploy Docker container on remote server
  hosts: remote_server
  become: true

  tasks:
    - name: Load Docker image from tar file
      command: docker load -i /home/vivek/{{ tar }}
      register: load_result

    - name: Check if image was loaded successfully
      fail:
        msg: "Failed to load Docker image: {{ load_result.stderr }}"
      when: load_result.rc != 0

    - name: Stop and remove existing container (if exists)
      community.docker.docker_container:
        name: my-container
        state: absent
      ignore_errors: yes

    - name: Stop and remove existing container (if exists)
      community.docker.docker_container:
        name: my-container
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
           -  "8065:80"
