---
- name: Deploy Docker image to remote server
  hosts: 192.168.1.93
  become: true
  vars:
    local_image_path: "/tmp/my-image.tar"  # Local path to save the Docker image tarball
    remote_image_path: "/tmp/my-image.tar" # Remote path to store the image file

  tasks:
    - name: Save Docker image on Jenkins server
      delegate_to: localhost
      command: "docker save -o {{ local_image_path }} {{ image }}"
      args:
        creates: "{{ local_image_path }}"  # Only creates if it doesn't already exist
      tags: save-image

    - name: Copy Docker image to remote server
      ansible.builtin.copy:
        src: "{{ local_image_path }}"
        dest: "{{ remote_image_path }}"
      tags: copy-image

    - name: Load Docker image on remote server
      command: "docker load -i {{ remote_image_path }}"
      tags: load-image

    - name: Stop existing Docker container
      docker_container:
        name: my-container
        state: stopped
      ignore_errors: yes
      tags: stop-container

    - name: Remove existing Docker container
      docker_container:
        name: my-container
        state: absent
      ignore_errors: yes
      tags: remove-container

    - name: Run Docker container
      docker_container:
        name: my-container
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"  # Update port mapping as needed
      tags: run-container
