- name: Deploy Docker container on remote server
  hosts: remote-server
  become: true  # Use sudo if necessary

 tasks:
    - name: Ensure Docker image is available (Load local image)
      docker_image:
        name: "{{ image }}"
        source: build
        path: /path/to/your/docker/context  # Local path where Dockerfile and context are located
        build:
          rm: yes
          pull: no  # Don't pull the image, just build from the local context


    - name: Stop existing Docker container
      docker_container:
        name: my-app
        state: stopped
        ignore_errors: yes

    - name: Remove existing Docker container
      docker_container:
        name: my-app
        state: absent
        ignore_errors: yes

    - name: Run Docker container
      docker_container:
        name: my-app
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"  # Adjust ports as needed
