- name: Deploy Docker container on remote server
  hosts: remote-server
  become: true

  tasks:
    - name: Load Docker image from tar file
      command: docker load -i /path/to/save/my-image.tar

    - name: Stop and remove existing Docker container
      docker_container:
        name: my-container
        state: absent
        ignore_errors: yes

    - name: Run Docker container
      docker_container:
        name: my-container
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
